// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: proto/car.proto

package car

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MakerClient is the client API for Maker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MakerClient interface {
	MakeCar(ctx context.Context, in *CarRequest, opts ...grpc.CallOption) (*CarReply, error)
}

type makerClient struct {
	cc grpc.ClientConnInterface
}

func NewMakerClient(cc grpc.ClientConnInterface) MakerClient {
	return &makerClient{cc}
}

func (c *makerClient) MakeCar(ctx context.Context, in *CarRequest, opts ...grpc.CallOption) (*CarReply, error) {
	out := new(CarReply)
	err := c.cc.Invoke(ctx, "/pb.Maker/MakeCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakerServer is the server API for Maker service.
// All implementations must embed UnimplementedMakerServer
// for forward compatibility
type MakerServer interface {
	MakeCar(context.Context, *CarRequest) (*CarReply, error)
	mustEmbedUnimplementedMakerServer()
}

// UnimplementedMakerServer must be embedded to have forward compatible implementations.
type UnimplementedMakerServer struct {
}

func (UnimplementedMakerServer) MakeCar(context.Context, *CarRequest) (*CarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeCar not implemented")
}
func (UnimplementedMakerServer) mustEmbedUnimplementedMakerServer() {}

// UnsafeMakerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MakerServer will
// result in compilation errors.
type UnsafeMakerServer interface {
	mustEmbedUnimplementedMakerServer()
}

func RegisterMakerServer(s grpc.ServiceRegistrar, srv MakerServer) {
	s.RegisterService(&Maker_ServiceDesc, srv)
}

func _Maker_MakeCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakerServer).MakeCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Maker/MakeCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakerServer).MakeCar(ctx, req.(*CarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Maker_ServiceDesc is the grpc.ServiceDesc for Maker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Maker",
	HandlerType: (*MakerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeCar",
			Handler:    _Maker_MakeCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/car.proto",
}
